import { NextResponse } from 'next/server';

/* ══════════════════════════════════════════════════════════════
   WORK ORDER API — Create & Dispatch Email Notifications
   
   Called by the monitor route when Uma issues a work order via
   the issue_work_order tool call. Logs the order and sends an
   email notification to the assigned team member.
   
   In production, wire this to AWS SES. For the hackathon demo,
   it logs to console with full details.
   ══════════════════════════════════════════════════════════════ */

// In-memory store for work orders (demo purposes)
const globalForOrders = global as unknown as { workOrderLog: any[] };
if (!globalForOrders.workOrderLog) {
  globalForOrders.workOrderLog = [];
}

async function sendEmailNotification(order: {
  orderId: string;
  type: string;
  description: string;
  assignedTo: string;
  assignedEmail: string;
  priority: string;
}) {
  const subject = `[Uma] ${order.priority.toUpperCase()} Work Order ${order.orderId}: ${order.type}`;
  const body = `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 🌿 UMA HYDROPONIC MANAGEMENT SYSTEM
 WORK ORDER NOTIFICATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Order ID:    ${order.orderId}
Priority:    ${order.priority.toUpperCase()}
Type:        ${order.type}
Assigned To: ${order.assignedTo}

DESCRIPTION:
${order.description}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This work order was automatically generated by Uma,
the AI agricultural intelligence system at Desert Dev Labs.
Please review and take action promptly.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  `.trim();

  // Check for SES configuration
  if (process.env.AWS_SES_REGION && process.env.AWS_ACCESS_KEY_ID && process.env.SES_FROM_ADDRESS) {
    try {
      // Dynamic import to avoid build failures when aws-sdk isn't installed
      const { SESClient, SendEmailCommand } = await import('@aws-sdk/client-ses');
      const ses = new SESClient({
        region: process.env.AWS_SES_REGION,
        credentials: {
          accessKeyId: process.env.AWS_ACCESS_KEY_ID!,
          secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY!,
        },
      });

      await ses.send(new SendEmailCommand({
        Source: process.env.SES_FROM_ADDRESS,
        Destination: { ToAddresses: [order.assignedEmail] },
        Message: {
          Subject: { Data: subject },
          Body: { Text: { Data: body } },
        },
      }));

      console.log(`📧 Email sent via SES to ${order.assignedEmail}`);
      return { sent: true, method: 'ses' };
    } catch (sesError) {
      console.error('SES send failed, falling back to console log:', sesError);
    }
  }

  // Fallback: Console log the email (demo mode)
  console.log('\n' + '═'.repeat(50));
  console.log('📧 WORK ORDER EMAIL (Demo Mode — No SES configured)');
  console.log('═'.repeat(50));
  console.log(`TO: ${order.assignedEmail}`);
  console.log(`SUBJECT: ${subject}`);
  console.log('─'.repeat(50));
  console.log(body);
  console.log('═'.repeat(50) + '\n');

  return { sent: true, method: 'console' };
}

export async function POST(req: Request) {
  try {
    const order = await req.json();

    if (!order.orderId || !order.assignedTo || !order.assignedEmail) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    // Log the work order
    globalForOrders.workOrderLog.push({
      ...order,
      createdAt: new Date().toISOString(),
    });

    // Send email notification
    const emailResult = await sendEmailNotification(order);

    return NextResponse.json({
      success: true,
      orderId: order.orderId,
      emailSent: emailResult.sent,
      emailMethod: emailResult.method,
    });
  } catch (err) {
    console.error('Work Order API Error:', err);
    return NextResponse.json({ error: 'Failed to process work order' }, { status: 500 });
  }
}

export async function GET() {
  return NextResponse.json({ orders: globalForOrders.workOrderLog });
}
